name: Basil Badawiyeh
favicon: null
layout_spectrum: 0.89863
typography_spectrum: 0.49004
title: 'Ventures, Interests and Grand Plans...'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0062c7'
    - '#e1d0c0'
    - '#785541'
    - '#c89f6b'
    - '#1f3a12'
  brandStrength: 0.5543470308184624
  lightness: 0.5649044238962233
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
