name: Basil Badawiyeh
favicon: null
layout_spectrum: 0.4863
typography_spectrum: 0.6210598782636225
title: Badawiyeh USA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#234187'
    - '#578ecf'
    - '#8bbbdf'
    - '#f4f3f1'
    - '#111308'
  brandStrength: 0.5543470308184624
  lightness: 0.5649044238962233
  saturation: 0.3125
  rhythmicContrast: 0.8032321059145033
purpose: []
